### ISSUE TITLE
De-selecting additional info option

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#36]
For the ‘additional info’ options that include a choice of cover, it does not seem to be possible to unselect an option (one can change the cover value, but not completely remove the selection, so that no value is recorded).

**Comment by sacrevert** [comment]
This still seems to be the case. Can we add a '0' option? @andrewvanbreda presumably this would be OK from a website point of view? (the website does not explicitly give 0 as an option, but there is a blank option -- does this insert a zero into the database, or does it create an NA?

**Comment by andrewvanbreda** [comment]
@sacrevert 
The blank option on the website isn't an explicit termlist term, it is just a blank cell added automatically by indicia.
If nothing is selected in the control and a save is made, then nothing is added to the database.
If editing an existing sample and the control previously had a selection and then blank is chosen, Indicia automatically sets the deleted flag to on for the value selection row in the database.

A equivalent blank row function needs adding to the app, you don't want to be adding a term to act as a blank otherwise the website will show the blank term and the usual blank option as well.

**Comment by sacrevert** [comment]
Ok. Thanks. So some way of unselecting a selected term needs adding, but this shouldn't introduce any new termlist terms. (Presumably the visual display could give a '0', as long as under the hood this was just leaving the database field blank). Not sure whether @kazlauskis will have the resource for this at the moment. Is a simple solution just to allow a second tap to deselect a selected option?
