### ISSUE TITLE
Inherited plots not available to new owner through app

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#53]
I have been made aware of a possible problem with the App today by a surveyor wishing to enter data. I’m not sure if it is only something he is experiencing, but I think it’s something that will likely affect others in the same bot.

Basically He has inherited plots within his 1km square. So even though you can see these plots on the website for him (albeit showing as “No” under “My plot” as they were created by his predecessor)… Within the app, he can only see the square name and it is showing locations as missing.
So it appears that as these locations are associated with the square but not his account per se, he cannot see these plots/locations and enter data for them in the App.

**Comment by andrewvanbreda** [comment]
My conclusions were as follows

Right I think there are actually 2 problems........this confused me. So there is actually something for Karolis to investigate.

1. I think the NPMS website has a minor problem.
I think this is actually showing the plots to the user when they should actually be hidden if a square is owned by more than one person and someone else has created the plots.
This is a minor problem that occurs in this given scenario.
The Extra Species page is correct in this case actually.

(note it has subsequently come to light that Oli's account on the same square doesn't have the problem...curious....raised in another issue anyway)

2. The app shares this report with Extra Species.
So therefore I think there is a problem with the app that Karolis will need to investigate why the app doesn't show plots when Extra Species is showing them fine (I was "thrown" by the problem in point 1).

Karolis: below are the parameters that Extra Species is supplying to the get_my_squares_and_plots page and it is working fine for for the surveyor.

The report hasn't changed since early 2019. It should be returning his plots I think
{"pss_mode":1,"plot_number_attr_id":118,"core_square_location_type_id":4009,"additional_square_location_type_id":4009,"parent_plot_location_type_id":3786,"current_user_id":"{profile_indicia_user_id}","vice_county_location_attribute_id":90,"no_vice_county_found_message":"1km square","user_square_attr_id":2,"only_show_my_useable_plots_squares":1}
