### ISSUE TITLE
Auto-tweeting of plot or species photos from app?

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#64]
Idea from Felicity

**Comment by kazlauskis** [comment]
@sacrevert do you have any preferences where would you like to see the sharing option available? One of the places could be at the top of an uploaded record page: 

<img width="323" alt="Screenshot 2021-04-07 at 11 46 27" src="https://user-images.githubusercontent.com/7383162/113854600-f23e7480-9796-11eb-84de-a07291783d15.png">

**Comment by sacrevert** [comment]
I suppose it depends whether we are allowing people to tweet at the sample or occurrence level. If sample level then I think we would like the tweet to have the sample (plot) photo, if occurrence, then the image of the plant (I suppose then we would want to force people to take a photo of the plant). Not sure whether @DavidRoy or @NPMSSupport have any other ideas or insights?

To answer your actual question :), I trust your judgement in terms of actual on-screen placement of the button.

**Comment by DavidRoy** [comment]
Sample level seems right to me. With a plot photo together with a summary of the occurrences?

**Comment by sacrevert** [comment]
Yeah, that sounds good. So the text string might be something like: 
"[assigned habitat]: [species 1] - [Domin score 1] / [species 2] - [Domin score 3] / [species 3] - [Domin score 4] / ..."
In the event it goes over 240 characters then we just truncate I think.

**Comment by kazlauskis** [comment]
@sacrevert I've added the sharing option. When selecting an **email** option it also sets the draft subject to **My NPMS survey on CURRENT_DATE** so this could also be used as a basic exporting option. I don't truncate the message to 240 because it is only Twitter that restricts this so we leave it to the user to remove the extra characters from the full message if too long. I have also enabled more than one photo for sharing so this will add all the plot photos. How does this look to you? 

![IMG_1127](https://user-images.githubusercontent.com/7383162/114597278-7e193a80-9c88-11eb-9db9-65f8978ea411.PNG)
![IMG_1128](https://user-images.githubusercontent.com/7383162/114597286-7fe2fe00-9c88-11eb-9db5-8e8b42005a19.PNG)
![IMG_1129](https://user-images.githubusercontent.com/7383162/114597291-81142b00-9c88-11eb-8063-c37f71011845.PNG)
![IMG_1130](https://user-images.githubusercontent.com/7383162/114597301-83768500-9c88-11eb-9b51-ca3d7cdb1900.PNG)

**Comment by sacrevert** [comment]
Really nice! Thanks Karolis.
@npmssupport @DavidRoy @kwal2
Any strong opinions on going with common names rather than scientific names here?

**Comment by DavidRoy** [comment]
Common names seem most appropriate for this?  Also does the tweet need to say ‘NPMS plot’ or some such?

**Comment by sacrevert** [comment]
Yes, can the tweet begin with #NPMS please @kazlauskis , otherwise I think this is fine.

**Comment by kazlauskis** [comment]
A good idea, I'll add this. Closing this now.
