### ISSUE TITLE
Add training mode to the app

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#65]
Samples now support training mode in Indicia so we can add this to the app. Website already has this functionality - ask Andy.

**Comment by andrewvanbreda** [comment]
This was coded for the website but never went live I think because enabling training on the website wouldn't of affected the app and confused users.

Website issue is here
https://github.com/BiologicalRecordsCentre/NPMS/issues/190

Once this is done on the app, we can look to allow the checkbox on the website.
