### ISSUE TITLE
[beta testing 2024] In app registration not working

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#80]
Whether through NPMS or PP, Register in app gives this error:

"Sorry. A password cannot be specified. It will be generated on login."

**Comment by kazlauskis** [comment]
@andrewvanbreda I am not sure why I am receiving this from the two websites. I typically just need to install the `user_registrationpassword_rest` module to enable user registeration with passwords. Do these websites have some specific configuration that prevents this?

**Comment by andrewvanbreda** [comment]
@kazlauskis @sacrevert
I do not know much about this.
I don't think the sites are setup in an unusual way though.

This thread mentions the same message, I think in this case it is saying it might be a bug in Drupal
https://www.drupal.org/project/drupal/issues/3055807

I haven't read the whole thread in detail though

**Comment by kazlauskis** [comment]
@andrewvanbreda OK, I got it now. For other sites we have allowed password entry when registering. Are you OK for me to switch it ON?

![Screenshot 2024-10-04 at 10 24 08](https://github.com/user-attachments/assets/97174e7b-c0e2-4df5-a95d-9911432e773d)

**Comment by andrewvanbreda** [comment]
Hi @kazlauskis @sacrevert ,

I had hoped to test this on my a DEV site, then hopefully find out the differences are small between the modes, then get Oli to approve the change.

However, what I found were more dramatic differences that require some work to resolve.

1. When switching modes, the email Drupal sends is different. I am now sent a generic Drupal registration message (see attached)

2. We can obviously overwrite the text with the existing registration email, but that would need alteration as the steps the user takes are different during registration, I am not sure whether other instructions would need altering.

3. I also noticed the new registration emails don't actually work.
I think what is supposed to happen is this:

A: User signs up, and on that registration form they can set password (before they only set it after getting the email).
B: They then get an email, at this stage the account is blocked on the system until the user clicks on the one-time login on the email which auto logs them in and activates the account. Then they continue as usual.
This appears not to happen.
Notice I got a second empty email with subject "No subject".
In the main email I got, the links don't actually work. The one-time login goes to 404.

@sacrevert : Are you OK with the registration process being changed if we can get this working?

@BirenRathod: Do you know why changing modes would cause the second blank email and the 404, I have just remembered you did some workarounds to get things like HTML working in Drupal emails, do you think that could be affecting things? I notice the  Mailer Policy area looks different to what I see on things liek EBMS
https://www.npms.org.uk/admin/config/people/accounts

Noting I have not checked Plant Portal, but if there are problems with that, they would be the same or less.

![Screenshot 2024-10-04 at 09 34 45](https://github.com/user-attachments/assets/b6b5ab4f-123f-47a2-ab1c-c4b0846a203f)

**Comment by sacrevert** [comment]
@andrewvanbreda Yes, please do what you need to

**Comment by BirenRathod** [comment]
@andrewvanbreda after changing a mode you need to add "Registration confirmation (Pending approval)" in the mailer policy. it was not added. Check first if that work after enabling the mode.
Not sure the mailer policy enabled on the PlantPortal but if not it needs to enable it.

**Comment by andrewvanbreda** [comment]
OK thanks @BirenRathod, I have found that, I will let you all know how I get on.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod
OK, I can get this to mostly work now on my Multidev site.
However there is just one major problem.
Alongside the registration email (which now replaces the email with no content in the screenshot), that extra email with all the tag replacements that don't work is still sent (the same one in the screenshot above).
We don't actually want that email at all (also the tags haven't been replaced in it either anyway).
I also noticed when I go to the page where you define the email texts
https://avb-links2-brc-npms-d10.pantheonsite.io/admin/config/people/accounts
that actually there is nothing present that matches the email text I am seeing, so I can't actually even locate it to attempt to prevent it sending.
Any ideas?

Cheers

**Comment by BirenRathod** [comment]
@andrewvanbreda you will fine that when you scroll down in "Account settings" page. -> Here the link https://www.npms.org.uk/admin/config/people/accounts.

And the change the tag as required.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod,
This is the problem, the emails on that page are not the ones being sent.
Note I am doing this work on my DEV site which is this one,
https://avb-links2-brc-npms-d10.pantheonsite.io/admin/config/people/accounts
My mistake, as initially putting the wrong link in thread above (which I have now corrected).

If I put "TEST" at the top of all the email texts in that configuration page, then that change is not reflected in the email I am receiving. 
It might be better if we email about this? (otherwise this thread is going to fill up)
Could you let me know if you have any thoughts about that in an email.

Cheers.

**Comment by andrewvanbreda** [comment]
Hi @sacrevert @kazlauskis @BirenRathod ,

I have managed to work out what is happening here (kind of).

I think switching the mode causes issue because the system is running a couple of different extra modules that are interacting in an odd way.

Firstly, there is a "User registration password" module (and associated "User registration password REST" module).

I think those modules allow the password entry to be placed directly on the first registration page (and going by the REST name, I assume the other module is needed by the app).

Secondly
There is also the Drupal Symfony Mailer module installed, which I think is needed for the HTML in emails to work across the site.

The problem I am having is that after we make the suggested mode switch, 2 emails are received by the user when they register.

I think the extra email is being sent by User Registration Password module
(This is the "register_confirmation_with_pass" entry at the bottom of this page https://www.npms.org.uk/admin/config/system/mailer) .

As the user is receiving 2 emails, the obvious thing to do is to split the registration email up, so the user receives one about about the NPMS scheme, and one about logging in for the first time.

Unfortunately, to add the the confusion, this second email is messed up when it is sent.
The tags in it do not replace, and even the login links are broken and go to page not found 404 
(see first screenshot).

I tried to customise this email, but the tags still don't work (screenshot 2)

The next this I tried was to delete this extra troublesome "register_confirmation_with_pass" email completely. 
However, this results in the system falling back on the built-in Drupal equivalent email. One upside of this is I can make an email that uses the required tags ok (see screenshot 3 below)

The difficulty is if I do that, I am deleting register_confirmation_with_pass email that I think the app needs.

Any thoughts from anyone welcome as I am struggling for a solution.

Possible questions

1. It would be useful if someone could confirm if register_confirmation_with_pass actually is used by the app.
It is at bottom here,
https://www.npms.org.uk/admin/config/system/mailer

2. Biren, is it possible to get register_confirmation_with_pass to work with HTML. I noticed it uses the "Email HTML" text format, but it is all broken when it sends.
I tried look in the Text Format Content Authoring area, but there didn't seem to be anything obviously wrong causing this issue. Although I notice the links are broken and going to 404 as well, so perhaps the issue is deeper than just HTML display.

I hope that isn't too confusing, it is hard to explain in any kind of straightforward way.

A good start is to find out what register_confirmation_with_pass is actually used for.


<img width="763" alt="Screenshot 1" src="https://github.com/user-attachments/assets/0e75a661-0244-4218-a893-365184dbc081">


<img width="741" alt="Screenshot 2" src="https://github.com/user-attachments/assets/5523674b-df24-476c-872d-e24155eb1c93">


<img width="750" alt="Screenshot 3" src="https://github.com/user-attachments/assets/8c3a9076-e467-46bf-b86b-20ccc5786e5b">

**Comment by BirenRathod** [comment]
@andrewvanbreda did try removing all policy from this ->https://avb-links2-brc-npms-d10.pantheonsite.io/admin/config/system/mailer? and then add it one by one as needed.

**Comment by BirenRathod** [comment]
@andrewvanbreda I just disable the "User" override and enabled it again  which has removed the extra "register_confirmation_with_pass" field. See if that is ok. I done this on here -> https://avb-links2-brc-npms-d10.pantheonsite.io

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod, (@sacrevert @kazlauskis)
OK thanks, that has fixed one issue I was having where I was unable to remove the built-in Drupal email that was always being sent even if register_confirmation_with_pass was removed.
This means that we are in a situation where we can theoretically switch to the new mode Karolis' wanted, and only have one email sent.

But there is still a problem.
Does the app make use of that register_confirmation_with_pass email, if it does, then we can't remove it.
i.e. when a user registers with the app, what email are they getting sent upon registration?

**Comment by BirenRathod** [comment]
@andrewvanbreda glad it wroks.

The app bit you can check that with @kazlauskis.

**Comment by kazlauskis** [comment]
@andrewvanbreda it uses the `register_confirmation_with_pass` notification for [resending account verification links](https://github.com/FlumensIO/user_registrationpassword_rest/blob/a15d44df3eb524a1be92edde4b959b2890748e62/src/Plugin/rest/resource/UserRegistrationPasswordResource.php#L80).

**Comment by andrewvanbreda** [comment]
Hi, @kazlauskis 
I have found I can block the email from inside the Drupal module I had already written to deal with particular NPMS custom behaviours
I can use this,

function npms_specific_field_customisations_mail_alter(&$message) {
  if ($message['id'] === 'user_registrationpassword_register_confirmation_with_pass') {
    $message['send'] = FALSE;
  }
}

This might be silly question, but will this also block the message if it is fired by the app?
If so, I need to find a way of detecting if it is fired by the website or app.
(if you don't know we could probably just deploy without any harm and see in testing)

**Comment by sacrevert** [comment]
Are we able to solve this in the next day or two and get the final version live? The absolute deadline is the end of the month, and I need to show it to JNCC before that in order for UKCEH to be paid.

**Comment by andrewvanbreda** [comment]
Hi @sacrevert 
I can't work on this this morning, but given that timeframe what I can do is deploy the change I suggest to live this afternoon, then if it causes problems with the app we can adjust it from there.
The wording of the registration email will need altering, I think it is best if I do that, and then if you don't like it, we can adjust it
(it is just the bit about what to do with the one-time link that needs altering).

**Comment by sacrevert** [comment]
Thanks @andrewvanbreda

**Comment by kazlauskis** [comment]
I agree, we should probably enable the "registration with password" on the website, this will fix the in-app registration. Then the password reset emails might be affected if Andy turns them off, but I hope that's something we can fix on the website.

**Comment by andrewvanbreda** [comment]
@sacrevert @kazlauskis 
I have changed NPMS.
The new instructions in the registration email are below. In addition to this is a new email (which hopefully we can attempt to stop) informing the user that their account is activated after they click on the link.
I reworded that activation email as it was all wrong, but for now I kept it simple.
I think there will be issues we need to iron out though. I already noticed an error occurs now if admin themselves try to create an account for someone else, in practice that particular issue wasn't a "blocker" as I don't think that ever happens in reality (also in that case, the error is only about the email that can't be sent, so a workaround is to manually email the user.

I realise I need to do Plant Portal too, which I have not done yet.

<img width="494" alt="Screenshot 2024-10-10 at 17 04 46" src="https://github.com/user-attachments/assets/50ef3ca8-43f0-48fe-a5e7-927213c80b72">


<img width="566" alt="Screenshot 2024-10-10 at 17 03 37" src="https://github.com/user-attachments/assets/037e860e-4c89-4e29-95f0-4882e7bd234d">

**Comment by andrewvanbreda** [comment]
@BirenRathod I have sent you an email, as am having trouble with Plant Portal as it seems setup differently to NPMS, so I can't do the same thing to get it working.

**Comment by BirenRathod** [comment]
@andrewvanbreda I have responded to your email.

**Comment by andrewvanbreda** [comment]
Hi @sacrevert (@kazlauskis),

With Biren's help, I have managed to get Plant Portal working.
So I switched the mode on Plant Portal live yesterday, so you can double check the registration whenever you are ready.

There are a few things to note:

1.
On NPMS, once you register a user on the app, I would want to double-check the Addresses are appearing on User Information Download (i.e the data has gone into the Warehouse correctly)

2. There may be problems resulting from the changing of the modes on both the websites, so they will need testing. Some possible issues are:

A.
I am blocking one of the unwanted registration emails programatically, but I am a little unclear whether that email is needed at other times, such as by the app.

B.
I am not sure, but going by some emails I received from Robin (who seems to be in charge of checking mails going into the BRC CEH email account ), when a user is registering, it is sending an email asking for approval to the site email account.
We don't want that,
I will double check with Robin again about this.
I am a bit confused by that, as the "administrator approval is required" option is not set.
As I say, as I am not seeing the emails myself, I am a little unclear and need to double check if that is an issue.

**Comment by sacrevert** [comment]
Just for info I also have access to the BRC account and I think Robin is off this week

**Comment by sacrevert** [comment]
@kazlauskis does this affect the new version of the app, or should I just got ahead and test again now?

**Comment by kazlauskis** [comment]
@andrewvanbreda I've tried the NPMS registration but the verification email doesn't reach me. I can see [this](https://www.npms.org.uk/admin/reports/dblog/event/281492) Mail error in the logs.

**Comment by andrewvanbreda** [comment]
Hi @sacrevert @kazlauskis ,
I think you can go ahead with testing, all the changes are on the website, so the app would pick them up straight away.
Having said that, Karolis has noticed a problem.

I tested the NPMS registration on the website several times last week, and this was OK, however I was making sure I wasn't selecting the Newsletter subscription.
I just did another signup and can confirm that problem is not limited to the app.
However in the website's case the registration does go ahead anyway, so I am not sure how long it would of been like this.

@BirenRathod @NPMSSupport 
There is a problem with the Mail Chimp signup on NPMS (see Karolis' error above). Not sure who setup Mail Chimp so am copying you both in. Would you be able to have a look at the configuration please?

Perhaps Oli when you get a chance, you could check that BRC/CEH email account please, as that is where the Plant Portal site emails go.
I did a registration from Plant Portal this morning, so there shouldn't be anything in there about having to approve that registration.

Thanks

Andy

**Comment by BirenRathod** [comment]
@kazlauskis & @andrewvanbreda That error about "401 API key invalid" down to deprecated API key used by Mailchimp. The alternativate is to use oAuth authentication for NewsLetter.

@sacrevert  or @NPMSSupport do you know the login details of Mailchimp? it needs to authenticate via log into MailChimp + NPMS sites.

**Comment by andrewvanbreda** [comment]
Hi @kazlauskis 
I notice this morning you did several Plant Portal registrations, but they are blocked.
Hopefully there should be an email in your inbox with a link to activate the accounts?

**Comment by kazlauskis** [comment]
@andrewvanbreda I've just tried the registration again on both npms and pp sites and haven't received anything. You can try the registration using the demo app as well: https://npms.app.flumens.io/demo.html

**Comment by andrewvanbreda** [comment]
Hi @kazlauskis,
I don't know enough about how this works to say a lot about this at the moment.
If the app needs to send one of Drupal's standard emails such as a registration/forgotten password, how does it do that?
Does it have a special module such as User Registration Password, or does it tell Drupal to do something like create an account, then it is down to Drupal to send an email itself?

**Comment by andrewvanbreda** [comment]
Hi @kazlauskis 
I tried the app registration and can reproduce the problem where the registration email doesn't arrive.

One thing I noticed is there are some optional controls on the website registration form missing from the app registration.
This include things like if you are an MTA Member, perhaps these should be added?
Also if we do that, we can switch off the Newsletter checkbox (mail chimp signup) and exclude that as a possible cause (I wouldn't think it would be, but who knows)

@BirenRathod 
I noticed this in the logs.
Could this cause an issue?
User notice: Key file "file:///files/private/private.key" permissions are not correct, recommend changing to 600 or 660 instead of 770 in League\OAuth2\Server\CryptKey->__construct() (line 74 of /code/vendor/league/oauth2-server/src/CryptKey.php)

**Comment by kazlauskis** [comment]
> does it tell Drupal to do something like create an account, then it is down to Drupal to send an email itself

@andrewvanbreda Yes, that's right, the app uses a standard core Drupal REST for creating user entities. The `user_registrationpassword_rest` calls this [function](https://github.com/FlumensIO/user_registrationpassword_rest/blob/master/src/Plugin/rest/resource/UserRegistrationPasswordResource.php#L75) to send the `register_confirmation_with_pass` template.

**Comment by andrewvanbreda** [comment]
@kazlauskis 
OK I see, so that is what I am blocking. 
So I think I understand now, all this problmatic behaviour probably needs fixing at the website end by me.
I think my code will need changing to say "block, but not if the request is coming from the app".
Leave it with me for now.

**Comment by andrewvanbreda** [comment]
@kazlauskis 
Actually the problem is not even going to be that simple, as that email I don't think works the html we use for the Registration email even if we unblock it.
I might have to find a way to trap it, then get Drupal to send another email from this Symphony Mailer module.
Oh crumbs.......am gonna have to do some mega thinking about this one.

**Comment by kazlauskis** [comment]
Thanks, I see. Just to say that this set-up works with vanilla Drupal installation and other BRC sites that I've done apps for, so maybe there something you could do to align the NPMS config to those other sites?

**Comment by andrewvanbreda** [comment]
Hi @kazlauskis,
OK thanks for that info, I will look at what those sites do.
We do have some added complications, as the registration email in NPMS' case is full of html. Will see...

**Comment by BirenRathod** [comment]
> I noticed this in the logs. Could this cause an issue? User notice: Key file "file:///files/private/private.key" permissions are not correct, recommend changing to 600 or 660 instead of 770 in League\OAuth2\Server\CryptKey->__construct() (line 74 of /code/vendor/league/oauth2-server/src/CryptKey.php)

Nope. although it has generated by other simple_oauth module but that is the same used on other website like iRecord.

**Comment by andrewvanbreda** [comment]
Hi @kazlauskis @BirenRathod @sacrevert,

We have issues here that I do not know how to resolve.

I have done some tests and I think the issue is how roughly how I described a few days back, but actually a little trickier than I thought.

If I undo my email blocker code, I can get the app to send through its email.
(the downside of this is it would mean a website user would get 2 emails upon registration: the normal email AND the one indended for app users)

However there is a big problem here.
The email sent by the app doesn't  have its replacements properly filled in and the links that are there (such as log in) do not work (see picture).
We could perhaps insert some of these links in by hand, but we can't do that with a one-time only activation link.

I THINK the broken email is because of the presence of the Symphony Mailer module on the NPMS website, and I suspect that doesn't work with the User Registration Password module properly.

I do not know how to progress resolving this, if emails sent by the app do not respect the standard Drupal replacement tags due to the way the website is configured.

Perhaps a starting point might be if Biren you could confirm why Symphony Mailer is used on NPMS but not other sites? (is it to do with the HTML emails?)

At the moment, I am wondering if possible I could find a way of using the top option instead

"Do not require a verification email, and let users set their password on the registration form."

This would immediately get rid of the problem of the one time links not working....other html could be hard-coded if needed.
The website in that mode does still send the user the usual scheme information in an email.

However in that case, the user will not be receiving an email from the app at all, because the user Registration Password email won't be firing.

Karolis: Is there a way to fire a general html compatible email from the app during registration that isn't the User Registration Password email?
Or alternatively could we put the information that the user gets in the registration email onto a page on the app?
Obviously Oli would need to approve anything, but I am not sure what is technically possible at the moment.

At the moment I am struggling to think of other ideas unless Biren knows why the replacements don't work in User Registration Password.

Cheers

<img width="633" alt="Screenshot 2024-10-14 at 15 31 50" src="https://github.com/user-attachments/assets/595a802f-cb4a-433c-8ba7-3e83a3d3258b">

**Comment by sacrevert** [comment]
@andrewvanbreda I would be happy with a solution which stripped back the NPMS registration email to something basic and more in line with other BRC/Drupal sites. It's all very well having a lot of links and HTML in the email, but if it creates this amount of hassle then it is probably not worth it. Anyway, consider this permission to do something extreme which removes historic complexities and brings NPMS in line with other sites. We can worry about what information new registrants might be lacking as a result later on, and perhaps create new emails to deal with that that are not registration emails.

**Comment by andrewvanbreda** [comment]
Hi @sacrevert 
OK, as the app demo is attached to live, I will make these extreme changes for now in the knowledge there may be a little bit of risk for the next day or so in regards to possible sign-up oddities.
So I will:
- Switch registration mode to not need verification and adjust the registration email wording accordingly (it can be fully stripped back later)
- Assume the app won't send any email at all and that they will be able to access info from somewhere else such as a website page.

I will obviously examine Plant Portal separately but I expect similar.

@BirenRathod @kazlauskis 
Given this, there is no need to reply to the long message I sent above for now as I will be able to test these changes straight away on the app demo.

**Comment by BirenRathod** [comment]
@andrewvanbreda Although, you mentioned about no requirement of sending message but I thought I need to answer the question you asked.
1. The Drupal symfony mailer module support html email format. I didn't find any other module like that.
2. The symfony mailer module also support smtp transport to deliver the email.
3. Other website like iRecord uses this module for quite sometime.

Regarding NPMS, I seen there is a default user policy enabled in mailer override tab setting. This is for sending email as soon as user register regardless the mode. do you need that?

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod I will email you to avoid filling up thread

**Comment by andrewvanbreda** [comment]
@BirenRathod @sacrevert @kazlauskis 
Plant Portal is done.
I checked and it registers ok with the app demo link Karolis gave me above.
Note I didn't try to do anything with the app beyond registering and logging in.
The way it works is not actually how I described above.
It works like the other websites, it sends a bare bones confirmation email where the user clicks on a link that activates their account.

I only noticed one little thing about the registration process you may (or may not) wish to change. I think the app always defaults the username to be the email address, the website allows a separate username to be specified. I don't think this matter from a technical point of view.

I will do NPMS this afternoon, the process should be similar.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod @sacrevert @kazlauskis
Sorry I have not been able to deploy NPMS yet.
The problem is that Pantheon is not allowing commits into any of the NPMS environments. I have tried again this morning in the hope it would clear itself up, but no luck.
Biren are you able to investigate this please? (ask Pantheon support?) It doesn't seem to be anything related to the content of the commit, it does it even if I try to commit just a one character text content change.
Note that Plant Portal seemed ok when I tried it yesterday after I had this NPMS trouble.

[Pantheon Error.txt](https://github.com/user-attachments/files/17407776/Pantheon.Error.txt)

**Comment by sacrevert** [comment]
@BirenRathod are you able to prioritise this as a matter of urgency please. I need to be able to show the functioning app to the funders asap.

**Comment by BirenRathod** [comment]
@andrewvanbreda  this could be down to last commit made on it. I'm investigating into this.

**Comment by BirenRathod** [comment]
@andrewvanbreda  I sent you separate email.

**Comment by BirenRathod** [comment]
@andrewvanbreda it has resolved now. you can commit your code. I sent you an email to let you know too.

**Comment by andrewvanbreda** [comment]
@BirenRathod
Brilliant, thanks for resolving that.
I will let you all know once NPMS is sorted out.

**Comment by andrewvanbreda** [comment]
Hi @sacrevert @kazlauskis @BirenRathod ,

NPMS is done now.

I noticed when registering, NPMS was sending both the registration email and another email saying my account was blocked!
It technically is blocked until the activation link it clicked, but I don't really think Drupal should be sending out the email in that scenario.

Given that, I decided to play it safe and switch off the following optional "Notify user when..." options on both PP and NPMS.
So the user is no longer notified of...
Account Block
Account Activate

However, I left notify on Account Cancel in place.

This means they also will no longer get the second email about activation after they click on the activation link, I think that is better as they are told on the website screen about the activation anyway.
So there is only the one bare bones registration email now.

I also note a few difference with the NPMS app registration to the website which you may wish to address.

1. Similar to mentioned for Plant Portal, there is no username field.
2. (NPMS ONLY) If you register on the app, the "I agree" (to Data Access Policy) is not selected when you look at the account on the website after registration.
3. (NPMS ONLY) Some optional checkboxes are missing on the app "MTA Member," "Request Survey Form", "Subscribe", " Volunteer questionnaire opt-in"
4. "Training Mode" I noticed is missing on both Plant Portal and NPMS
I guess you may not actually want to include all of them, such as "Volunteer questionnaire opt-in" which is only accessed from the website.

I am obviously being picky here, the app registration looks really good.

I also checked the address fields were syncing to the Warehouse, and that is working apart from the checkboxes I noted above which were missing and as such were defaulting to off.

I guess check with Oli what he wants including, then can always be switched on from the website after anyway.
Obviously one possibility is to not include them on the app if you don't feel they are important. I guess the data access policy one is the really important one.

**Comment by sacrevert** [comment]
Thanks @andrewvanbreda 
I suggest leaving all extra fields out of the app. IIRC, users are prompted about the Data Access Policy on the website anyway, and users cannot use the app (for anything useful) without having visited the website anyway. 
I assume this means that the final app version can go live on the stores now @kazlauskis ?

**Comment by andrewvanbreda** [comment]
@sacrevert 
The data access policy warning doesn't appear to be present at the moment on the website, although I do not know why, it is possible it was scrapped at some point.
I will make a note to lookup what has happened to it.

**Comment by sacrevert** [comment]
@andrewvanbreda The NPMS one is here: https://www.npms.org.uk/content/data-access-policy
There isn't one on the Plant Portal at this point and never has been

**Comment by andrewvanbreda** [comment]
@sacrevert 
I edited my original post as I forgot to type the word "warning", I meant the warning doesn't seem to be showing, and I am not sure why at moment. I definetely remember it working at some point as there was even a request closed to put a logout link on it.
I will look to work out what happened.
Personally I wouldn't delay the app release over this though, as if it needs fixing, the change won't be on the app anyway. I don't think the warning ever prevented usage of the website if I remember correctly....I think anyway.

**Comment by sacrevert** [comment]
@andrewvanbreda we can't afford any more delays now anyway, but we should fix the warning on the site at some point -- perhaps you can add to the NPMS GitHub?

@kazlauskis if you can confirm that all is now fine with the app and that it can go live (once I have looked at the beta again?) that would be great

**Comment by kazlauskis** [comment]
@sacrevert I've tested the user account features, and they seem to be fine now. If you can confirm that the Beta is OK, then I will release it to live.

Edit: I have recently made some small account related changes to the app, the latest version is v2.0.0 (62)

**Comment by sacrevert** [comment]
Seen working
