### ISSUE TITLE
[beta testing 2024] NPMS in-app "Delete account option"

### ISSUE THREAD

**Issue by sacrevert** [NERC-CEH/npms-app#87]
We are slightly concerned about having this option within the app, as folk may think it means something like "remove app from phone", whereas actually there are quite a lot of implications related to deleting NPMS accounts. Can we remove this option from the app, and just direct users to the website to delete their NPMS account if desired? @andrewvanbreda not sure what you think about this?

**Comment by andrewvanbreda** [comment]
Hi @sacrevert ,

My main thought is the website doesn't let people remove their accounts at all, so I guess we shouldn't direct them there to do that.
(I can't remember the reasoning for this, but I think it is because when you do this on Drupal it gives the user lots of potentially confusing options such as disable rather than delete).

I think there are instructions somewhere that tell the user to ask support if they want to do this.

So I would have thought the app wouldn't have this option either, and it would be limited to remove from phone only, and maybe a note to say to contact NPMS Support if account removal is required.

**Comment by sacrevert** [comment]
Perfect, thanks @andrewvanbreda Agreed

**Comment by kazlauskis** [comment]
@sacrevert because we allow account registration in the app we have to provide an account delete option there too. This has been an [app store requirement](https://developer.apple.com/support/offering-account-deletion-in-your-app/) since 2022. Maybe we could get away with a more "manual" process by providing a link or redirect to a support email when pressing the delete button?

**Comment by sacrevert** [comment]
Understood. A link to support@npms.org.uk would be fine
